name: iCatcher
favicon: null
layout_spectrum: 0.11433329316787422
typography_spectrum: 0.3032823451794684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.961302112787962
  lightness: 0.11421992513351142
  saturation: 0.5074917441233993
  rhythmicContrast: 0.8382542517501861
purpose: []
