name: iCatcher
favicon: null
layout_spectrum: 0
typography_spectrum: 0.3032823451794684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f66e14'
    - '#020303'
    - '#c7c7c7'
    - '#676868'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
